### PR TITLE
Refactor the doc, add socat forking example

### PR DESCRIPTION
**Pull request by mcnemesis**

### CODE REVIEW

**Comment by joshcartwright** [comment]
LGTM.  Don't expect this to get pulled, though.  @avleen hasn't been to active on this project (last commit a couple years ago).

**Comment by mcnemesis** [comment]
@joshcartwright so which is the most active branch as of now?

**Comment by avleen** [comment]
I actually only just saw this and would be happy to merge pull requests :)

**Comment by mcnemesis** [comment]
@avleen awesome!

**Pull request merged**
